-- Matches what Hibernate generated before Flyway took over, because
-- ddl-auto=validate compares this against the entities on every boot and refuses
-- to start on a mismatch. Three details are less obvious than they look:
--
--   created_at is "with time zone" because Hibernate 6 maps java.time.Instant to
--   TIMESTAMP_UTC, not to a plain timestamp.
--
--   policy_type is varchar(255) because that is the default width for
--   @Enumerated(EnumType.STRING) with no explicit length. Narrowing it means
--   changing the entity in the same migration, not just this file.
--
--   The ids use IDENTITY rather than bigserial, which is what
--   GenerationType.IDENTITY produces on Postgres 10 and later.

CREATE TABLE app_users (
    id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email         varchar(256) NOT NULL UNIQUE,
    password_hash varchar(255) NOT NULL,
    role          varchar(20)  NOT NULL,
    created_at    timestamp(6) with time zone NOT NULL
);

CREATE TABLE rate_schedules (
    id                        bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    state                     varchar(2)    NOT NULL,
    policy_type               varchar(255)  NOT NULL,
    tier_start                numeric(14,2) NOT NULL,
    tier_end                  numeric(14,2),
    rate_per_thousand         numeric(10,4) NOT NULL,
    simultaneous_discount_pct numeric(5,4)  NOT NULL,
    effective_date            date          NOT NULL,
    CONSTRAINT rate_schedules_policy_type_check
        CHECK (policy_type IN ('OWNER', 'LENDER')),
    CONSTRAINT rate_schedules_state_policy_type_tier_start_key
        UNIQUE (state, policy_type, tier_start)
);

-- A lookup always filters on these three and orders by tier, and the unique
-- constraint above already covers (state, policy_type, tier_start), so no
-- separate index is added here.
